name: Accommodation CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.yaml
      - run: echo ${{ secrets.APPLICATION2 }} > ./src/main/resources/application.yaml
      - run: cat ./src/main/resources/application.yaml

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash


      - name: Docker 이미지 빌드 및 푸시
        env:
          CR_PAT: ${{ secrets.WONJUN_TOKEN }}
          IMAGE_NAME: my-spring-app
          IMAGE_TAG: latest
        run: |
          echo $CR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build -t ghcr.io/$GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push ghcr.io/$GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          username: student
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          port: 8080
          script_stop: true
          script: chmod +x /home/student/docker_script.sh && sh /home/student/docker_script.sh